//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaytmEnach
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountDetail()
        {
            this.SIPRegistrationDatas = new HashSet<SIPRegistrationData>();
        }
    
        public long ID { get; set; }
        public string AccHolderName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string AccountType { get; set; }
        public string AuthMode { get; set; }
        public string MandateMode { get; set; }
        public string NPCI_REF_ID { get; set; }
        public string RejectedBy { get; set; }
        public string MandateFormDownloadURL { get; set; }
        public string MandateFormUploadURL { get; set; }
        public string PolicyForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPRegistrationData> SIPRegistrationDatas { get; set; }
    }
}
