//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaytmEnach
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPData()
        {
            this.SIPRegistrationDatas = new HashSet<SIPRegistrationData>();
        }
    
        public int ID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public int Frequency { get; set; }
        public int FrequencyUnit { get; set; }
        public decimal Amount { get; set; }
        public int CustomerID { get; set; }
    
        public virtual FrequencyUnitMaster FrequencyUnitMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPRegistrationData> SIPRegistrationDatas { get; set; }
    }
}
